// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function FindDuplicates(arg1) {
  return window['go']['main']['App']['FindDuplicates'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OrganizeFolder(arg1, arg2) {
  return window['go']['main']['App']['OrganizeFolder'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectDirectoryDuplicate() {
  return window['go']['main']['App']['SelectDirectoryDuplicate']();
}
